import { appSchema, tableSchema } from '@nozbe/watermelondb'

export const schema = appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: 'categories',
      columns: [
        { name: 'server_id',  type: 'string',  isOptional: true },
        { name: 'tenant_id',  type: 'string' },
        { name: 'name',       type: 'string' },
        { name: 'color',      type: 'string' },
        { name: 'icon',       type: 'string',  isOptional: true },
        { name: 'synced_at',  type: 'number',  isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'warehouses',
      columns: [
        { name: 'server_id',  type: 'string',  isOptional: true },
        { name: 'tenant_id',  type: 'string' },
        { name: 'name',       type: 'string' },
        { name: 'location',   type: 'string',  isOptional: true },
        { name: 'is_default', type: 'boolean' },
        { name: 'synced_at',  type: 'number',  isOptional: true },
        { name: 'created_at', type: 'number' },
        { name: 'updated_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'products',
      columns: [
        { name: 'server_id',   type: 'string',  isOptional: true },
        { name: 'tenant_id',   type: 'string' },
        { name: 'category_id', type: 'string',  isOptional: true },
        { name: 'name',        type: 'string' },
        { name: 'sku',         type: 'string',  isOptional: true },
        { name: 'qr_code',     type: 'string',  isOptional: true },
        { name: 'description', type: 'string',  isOptional: true },
        { name: 'unit',        type: 'string' },
        { name: 'cost_price',  type: 'number',  isOptional: true },
        { name: 'sale_price',  type: 'number',  isOptional: true },
        { name: 'min_stock',   type: 'number' },
        { name: 'image_url',   type: 'string',  isOptional: true },
        { name: 'is_active',   type: 'boolean' },
        { name: 'synced_at',   type: 'number',  isOptional: true },
        { name: 'created_at',  type: 'number' },
        { name: 'updated_at',  type: 'number' },
      ],
    }),
    tableSchema({
      name: 'inventory_items',
      columns: [
        { name: 'server_id',    type: 'string',  isOptional: true },
        { name: 'tenant_id',    type: 'string' },
        { name: 'product_id',   type: 'string' },
        { name: 'warehouse_id', type: 'string' },
        { name: 'quantity',     type: 'number' },
        { name: 'reserved_qty', type: 'number' },
        { name: 'synced_at',    type: 'number',  isOptional: true },
        { name: 'updated_at',   type: 'number' },
      ],
    }),
    tableSchema({
      name: 'transactions',
      columns: [
        { name: 'server_id',      type: 'string',  isOptional: true },
        { name: 'tenant_id',      type: 'string' },
        { name: 'product_id',     type: 'string' },
        { name: 'warehouse_id',   type: 'string' },
        { name: 'type',           type: 'string' },
        { name: 'quantity',       type: 'number' },
        { name: 'unit_cost',      type: 'number',  isOptional: true },
        { name: 'reference',      type: 'string',  isOptional: true },
        { name: 'notes',          type: 'string',  isOptional: true },
        { name: 'scanned_via_qr', type: 'boolean' },
        { name: 'synced',         type: 'boolean' },
        { name: 'created_at',     type: 'number' },
      ],
    }),
    // ── v2: Kanban ────────────────────────────────────────────
    tableSchema({
      name: 'kanban_stages',
      columns: [
        { name: 'server_id',  type: 'string',  isOptional: true },
        { name: 'tenant_id',  type: 'string' },
        { name: 'name',       type: 'string' },
        { name: 'color',      type: 'string' },
        { name: 'position',   type: 'number' },
        { name: 'is_terminal',type: 'boolean' },
        { name: 'synced_at',  type: 'number',  isOptional: true },
        { name: 'created_at', type: 'number' },
      ],
    }),
    tableSchema({
      name: 'kanban_cards',
      columns: [
        { name: 'server_id',   type: 'string',  isOptional: true },
        { name: 'tenant_id',   type: 'string' },
        { name: 'stage_id',    type: 'string' },  // local WatermelonDB id da stage
        { name: 'stage_server_id', type: 'string', isOptional: true }, // server id da stage
        { name: 'product_id',  type: 'string',  isOptional: true },
        { name: 'title',       type: 'string' },
        { name: 'description', type: 'string',  isOptional: true },
        { name: 'quantity',    type: 'number',  isOptional: true },
        { name: 'priority',    type: 'string' },
        { name: 'due_date',    type: 'string',  isOptional: true },
        { name: 'assignee_id', type: 'string',  isOptional: true },
        { name: 'position',    type: 'number' },
        { name: 'synced',      type: 'boolean' },
        { name: 'synced_at',   type: 'number',  isOptional: true },
        { name: 'created_at',  type: 'number' },
        { name: 'updated_at',  type: 'number' },
      ],
    }),
  ],
})
